### ISSUE TITLE
NullRefException on MirrorReflection - Water in level 1 pink

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#6]
Open up the Level1 Scene

You'll have two errors and the water will be entirely pink

![2a8ef0fcad56e7189efaeab6aab66397](https://user-images.githubusercontent.com/29916701/55471121-f44a2780-5600-11e9-82b0-97b6e13c4fdd.jpg)

**Comment by UnityGuillaume** [comment]
Should be fixed by the attached commit (it's on a 19.1-update branch)

For some reason, the water material had been deleted by the latest commit, so I just re-added it. Should be ok now (performance in scene view is terrible, the water do a lot of texture fetch, but something change between 18.3 & 19.1 cause I didn't remember it being so bad, need to have a proper look when we will have time).

**Comment by Jacekpapapolski** [comment]
![54dd94a76f9326a6669fcd64d8e58bf8](https://user-images.githubusercontent.com/29916701/55477854-139d8080-5612-11e9-81e4-be896c306c84.jpg)

Water no longer pink but errors still in console

**Comment by UnityGuillaume** [comment]
@Jacekpapapolski That's strange, the error is because the material on the water plane is null...which it's clearly not since it render it properly.

can you check on the water object, in the mesh renderer, if there is a null or missing materials in the materials list?

If not that seems like a left over error, shouldn't happen with a clean pull.

**Comment by Jacekpapapolski** [comment]
Re-importing fixed the issue once again... Unity is having a bad time on my machine... Closing
